sudo: required
services:
  - docker
before_install:
  - docker build -t harry831/docker-react -f Dockerfile.dev .
script:
  - docker run harry831/docker-react npm run test -- --coverage
after_success:
  - docker build -t harish831/multi-client ./client
  - docker build -t harish831/multi-nginx ./nginx
  - docker build -t harish831/multi-worker ./worker
  - docker build -t harish831/multi-server ./server
 
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push harish831/multi-client
  - docker push harish831/multi-nginx
  - docker push harish831/multi-worker
  - docker push harish831/multi-server
